FROM golang:1.22-alpine AS builder

WORKDIR /build

# Copy go mod/sum
COPY go.mod go.sum ./

# Copy source
COPY cmd/backend/ ./cmd/backend/

# Build backend
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /backend ./cmd/backend

# Final stage
FROM alpine:3.19

RUN apk add --no-cache curl

COPY --from=builder /backend /backend

EXPOSE 9000

CMD ["/backend"]
